version: '3.8'

services:
  web:
    image: nguyenminh079/game-art:v1.0
    container_name: game-art
    command: gunicorn GameArt.wsgi:application --bind 0.0.0.0:8000 --timeout 120
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  celery:
    image: nguyenminh079/game-art:v1.0
    container_name: celery_worker
    command: celery -A GameArt worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - web

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"