# Generated by Django 5.2 on 2025-04-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('publisher', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('image_url', models.URLField()),
                ('category', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
