# Generated by Django 5.0 on 2025-04-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_remove_transaction_order_transaction_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='brand',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer_email',
            field=models.EmailField(default=1234, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='exp_month',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='exp_year',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='last4',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
