# Generated by Django 5.0 on 2025-04-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='game',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='game',
            name='price_id',
        ),
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(default='game_images/default.png', upload_to='game_images'),
        ),
        migrations.AddField(
            model_name='game',
            name='stripe_price_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='stripe_product_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
