# Generated by Django 5.0 on 2025-04-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_game_quantity_alter_game_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='stripe_price_id',
            field=models.CharField(default=1, editable=False, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='stripe_product_id',
            field=models.CharField(default=1, editable=False, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
