# Generated by Django 5.0 on 2025-04-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_game_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='game_hero_images')),
            ],
        ),
    ]
