# Generated by Django 5.0 on 2025-04-20 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_category_game_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='game_price_id',
        ),
        migrations.AddField(
            model_name='usergame',
            name='key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_game', to='games.key'),
            preserve_default=False,
        ),
    ]
