# Generated by Django 5.0 on 2025-04-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_remove_key_game_price_id_usergame_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
